export const REVENUE1 = "DASHBOARDREVENUE1"
export const REVENUE2 = "DASHBOARDREVENUE2"
export const REVENUE3 = "DASHBOARDREVENUE3"
export const REVENUE4 = "DASHBOARDREVENUE4"
export const REVENUE_USERS = "DAHSBOARDREVENUE_USERS"

